name: my-build-chain
run-name: this workflow is called from elsewhere
on:
  workflow_call:
    inputs:
      some-value:
        required: true
        type: string      
  
jobs:
  a-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing something with some-value ${{ inputs.some-value }}"
      - run: echo ${{ inputs.some-value }}
      - run: sleep $(( RANDOM % 20 ))
  another-job:
    needs: [a-job]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing something else"
      - run: sleep $(( RANDOM % 20 ))

  