name: regression-tests
run-name: Runs regression tests
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string      
  
jobs:
  a-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing something with some-value ${{ inputs.environment }}"
      - run: echo ${{ inputs.environment }}
      - run: sleep $(( RANDOM % 20 ))
  another-job:
    needs: [a-job]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing something else"
      - run: sleep $(( RANDOM % 20 ))

  